name: epub_io
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/Marc-R2/epub_io
issue_tracker: https://github.com/Marc-R2/epub_io
version: 6.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  charset: ^2.0.1
  collection: ^1.18.0
  freezed_annotation: ^2.4.4
  image: ^4.1.7
  path: ^1.9.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  test: ^1.25.2
  very_good_analysis: ^6.0.0
