= epub_io

ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

ifdef::status[]
image::https://codecov.io/gh/Marc-R2/epub_io/graph/badge.svg?token=AnWRyyjoQ1[link="https://codecov.io/gh/Marc-R2/epub_io"]
// image::https://img.shields.io/pub/v/epub_plus.svg[link="https://pub.dartlang.org/packages/epub_plus"]
image::https://img.shields.io/github/license/Marc-R2/epub_io.svg[https://github.com/Marc-R2/epub_io?tab=License-1-ov-file]
endif::[]

_This package https://github.com/Marc-R2/epub_io[epub_io]
is a fork of https://github.com/4akloon/epub_plus[epub_plus] by https://github.com/4akloon[@4akloon]
which is a fork of https://github.com/ScerIO/epubx.dart[epubx] by https://github.com/ScerIO[@ScerIO]
which is a fork of https://github.com/orthros/dart-epub[dart-epub] by https://github.com/orthros[@orthros].
Thank you to all of them and all the https://github.com/Marc-R2/epub_io/graphs/contributors[contributors] for their work._

> Epub Reader and Writer for Dart inspired by https://github.com/versfx/EpubReader[this fantastic C# Epub Reader]
> -- orthros

// This does not rely on the ```dart:io``` package in any way, so it is avilable for both desktop and web-based implementations

In contrast to the other versions, this package relies on the `dart:io` package for (some) file operations.
This allows for dynamic file access, without the need to load the entire file into memory.
This results in a much faster initial loading time for RefObjects, when only parts of the epub archive are needed.

_But one goal is to provide dynamic classes that can be used in web-based implementations as well._

== Installing

Not yet published to pub.dev

You can use the package from the https://github.com/Marc-R2/epub_io/tree/generated-files[_generated-files_] branch by adding the following to your pubspec.yaml

[source,yaml]
----
dependencies:
  epub_io:
    git:
      url: https://github.com/Marc-R2/epub_io.git
      ref: generated-files
----

// Add the package to the ```dependencies``` section of your pubspec.yaml

// [source,yaml]
// ----
// dependencies:
//  epub_io: any
// ----

== Example

[source,dart]
----
include::example/main.dart[]
----
